#!/usr/bin/env python3

# UGLY hack to get things to work

import subprocess, sys

args = list(sys.argv[1:])
for i in range(len(args)):
    #if args[i] == '-o':
    #    args[i] = '-e'
    if args[i] == '-e':
        args[i] = '-o'

if '-a' in args:
    del args[args.index('-a')]

args = ['/usr/bin/inkscape'] + args

sys.stderr.write("rsvg:" + str(args) + '\n')

exit(subprocess.call(args))
